- name: Elk
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
    
  vars_prompt:
    - name: kong_delete_image
      prompt: "Do you want to delete containers and images (y/n) \n
      'y': Delete image\n
      'n': Do not delete image\n\n"
      private: no
      default: 2

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"}
    - { role: role_nginx, tags: "role_nginx"}
    - { role: kong, tags: "kong"}
    - { role: role_init, tags: "role_init"}
    - { role: role_preend, tags: "preend"}
    - { role: role_end, tags: "role_end"}
