- name: Kong
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_nginx, tags: "role_nginx" }
    - { role: role_docker, tags: "role_docker" }
    - { role: kong, tags: "kong" }
    - { role: role_init, tags: "role_init" }
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
