- src: http://github.com/websoft9dev/role_common
- src: http://github.com/websoft9dev/role_cloud
- src: https://github.com/Websoft9/role_nginx.git
- src: http://github.com/websoft9dev/role_init
- src: http://github.com/websoft9dev/role_preend
- src: http://github.com/websoft9dev/role_end
